### ISSUE TITLE
How to handle math in bookmarks?

### ISSUE THREAD

**Issue by tgkolda** [tgkolda/siam-latex#19]
From James Haines email on 7/17/15, item 2.

Regarding the bookmark feature, we noticed that we needed to type:

\section{For \texorpdfstring{{\boldmath$X\cup Y$}}{\textdollar X \textbackslash cup Y\textdollar} or something else}

So that the bookmark comes out as “For $X \cup Y$ or something else” verbatim. There doesn't seem to be an easier way to do this and it does come up on occasion so we received warnings when running our test papers if we didn't put math or certain other special commands inside a \texorpdfstring command (see: http://www.tex.ac.uk/FAQ-texorpdf.html).  For further example,

\section{What?\texorpdfstring{\nopunct}{}}
\section{For \texorpdfstring{{\boldmath$x$}}{x} large}
\section{For \texorpdfstring{{\boldmath$y=\frac{1}{2}$}}{y=1/2} or something else}

**Comment by tgkolda** [comment]
From John at Techsetters: I've found that the bookmark text can best be addressed by using the optional argument for sections, placing the \texorpdfstring commands in the square brackets. This works on our "other" books, might be worth a try here.

**Comment by JHainesSIAM** [comment]
So basically I told John what Steve came up with to get around the issue and he confirmed that this is what they do at Techsetters as well.  As long as there is a mention in the documentation how to handle this, we can close this issue.

**Comment by tgkolda** [comment]
Explained how to do the \texorpdfstring solution, which seems the easiest unless I'm missing something.
