### ISSUE TITLE
Requires recent version of LaTeX

### ISSUE THREAD

**Issue by rjleveque** [tgkolda/siam-latex#2]
My first attempt to run latex or pdflatex on `siamlatex/docsiamart.tex` failed with a host of error messages, on a MacBook using pdfTeX 3.1415926-2.4-1.40.13 (TeX Live 2012).  The error messages start at about line 675 in https://github.com/rjleveque/siam-latex/blob/old_latex_log/siamlatex/docsiamart.log

I just updated to pdfTeX 3.14159265-2.6-1.40.15 (TeX Live 2014) and now it compiles fine.

I suspect many authors will be at least as out of date as I was.  Is it a problem if they can't use the SIAM style without upgrading?

**Comment by tgkolda** [comment]
Hi Randy - 

1) In order to make the examples look nice, the docsiamart.tex uses some packages and features that are not needed for just regular documents. We may want to create a "simple" example to see the minimum that's required.

2) I fully expect that this will be the standard for 10+ years, so I think we should use the most up-to-date features available. Of course, this is to say that we shouldn't consider all options.

Best wishes,
Tammy

**Comment by rjleveque** [comment]
It's great to have a guide like this that has the latex source displayed along with the resulting output so that authors can figure out how to do something without digging through the tex file.  But I think we also want a simple template tex file that authors can copy from to get started.  

Regarding use of packages like `cleveref` -- I didn't know about it but it seems great.  But are we going to require this?  Many authors will want to keep doing things they way they have in the past, e.g. `Section~\ref{sec:intro}` rather than `Cref{sec:intro}`, particularly if submitting a paper written before seeing the new SIAM style.  The document currently says "don't do it this way".  Is that a recommendation or a requirement?

**Comment by tgkolda** [comment]
Using `cref` is definitely a requirement --- otherwise the hyperlinks won't work correctly, which is one of our major goals is this update. Of course, SIAM never forces an author to adhere to the requirements, but it's much more work for the SIAM staff if authors don't do it.

**Comment by tgkolda** [comment]
And I agree we need a simple template file too.

**Comment by dgleich** [comment]
If we replace:

```
\RequirePackage[colorlinks,hidelinks,naturalnames=false,hypertexnames=false,breaklinks]{hyperref}
```

with 

```
\RequirePackage[colorlinks=false,frenchlinks=false,pdfborder={0 0 0},naturalnames=false,hypertexnames=false,breaklinks]{hyperref}
```

This makes it compatible with older versions of hyperref. (Such as those current in Ubuntu 12.04.) This was the only error I had using the new style file. hidelinks in more recent versions maps to exactly these options.

```
\DeclareVoidOption{hidelinks}{%
  \Hy@colorlinksfalse
  \Hy@ocgcolorlinksfalse
  \Hy@frenchlinksfalse
  \def\Hy@colorlink##1{\begingroup}%
  \def\Hy@endcolorlink{\endgroup}%
  \def\@pdfborder{0 0 0}%
  \let\@pdfborderstyle\ltx@empty
}
```

**Comment by tgkolda** [comment]
Agreed. Please go ahead and make the change.

**Comment by tgkolda** [comment]
Added required version so it will throw errors for older versions of LaTeX.
