### ISSUE TITLE
Fix broken Appendix references

### ISSUE THREAD

**Issue by tgkolda** [tgkolda/siam-latex#20]
From James Haines email on 7/17/15, item 3.

If you’re in the appendices and have a subsection or a subsubsection, it has the word “Appendix” before its number. For instance, if you have:

\documentclass[final,leqno]{siamart} 
\begin{document}
\appendix
\section{Appendix}
\subsection{Subappendix}
\subsubsection{Subsubappendix}
\end{document}

It prints as:

Appendix A. Appendix.
Appendix A.1. Subappendix.
Appendix A.1.1. Subsubappendix.

It should be:

Appendix A. Appendix.
A.1. Subappendix.
A.1.1. Subsubappendix.

We also found that if you do:

\documentclass[final,leqno]{siamart}
\begin{document}
\appendix
\section{An appendix}\label{A}
\section{Another appendix}\label{B}
Let's refer to \cref{A,B}.
\end{document}

It prints as:

Appendix A. An appendix.
Appendix B. Another appendix. Let’s refer to Appendices Appendix A and Appendix B.

Typing “Let's refer to \ref{A} and \ref{B}.” prints as “Let’s refer to Appendix A and Appendix B.” and we don’t see how to get “Let’s refer to Appendices A and B.” as we would need to.

Further, if you do:

\documentclass[final,leqno]{siamart}
\numberwithin{theorem}{section}
\numberwithin{equation}{section}
\begin{document}
\appendix
\section{An appendix}
\begin{theorem}
A short theorem.
\end{theorem}
An equation:
\begin{equation}
x+y=z
\end{equation}
\end{document}

You’ll see that the theorem heading comes out as “Theorem Appendix A.1.”, and the equation number as “(Appendix A.1)”.

**Comment by tgkolda** [comment]
From John at Techsetters: The various "workaround" Appendix sectioning commands are commented-out in the new class. Let's try reinstating these, see if they work properly. I don't see a "universal" solution for this.

**Comment by JHainesSIAM** [comment]
I just noticed that these are now printing as:
A. An appendix.
A.1. A subappendix.
A.1.1. A subsubappendix.

I assume this is a side effect of getting the \cref commands and other numbering to work?

**Comment by tgkolda** [comment]
I fixed something else in the code. Is this what was wanted? It seems that there was some preference that the section level print "Appendix" in the title.

**Comment by JHainesSIAM** [comment]
Yes, the section level should print "Appendix A. Appendix" but at least the sub levels are showing up as they should now.

**Comment by tgkolda** [comment]
This has been fixed.

**Comment by louisabraham** [comment]
Hello, I have the same issue with the elsarticle class. Can you tell me how you fixed it?
