### ISSUE TITLE
Fix cref to multiple equations

### ISSUE THREAD

**Issue by tgkolda** [tgkolda/siam-latex#27]
From James Haines email on 7/17/15, issue 10.

Equation ranges with \cref are not displaying as they should.  They result in “(1--3)” instead of “(1)--(3)” as needed. 

\documentclass[final,leqno]{siamart}
\begin{document}
Three numbered equations:
\begin{align}
a &= b+c, \label{eq1} \
d &= e+f, \label{eq2} \
g &= h+i. \label{eq3} 
\end{align}
\Cref{eq1,eq2,eq3} are useful. We can solve \cref{eq1,eq2,eq3} like this.
\end{document}

The last line prints as “Equations (1--3) are useful. We can solve (1--3) like this.”  What needs to be done so that this results in “Equations (1)--(3) are useful. We can solve (1)--(3) like this.” instead?

**Comment by tgkolda** [comment]
From John at Techsetters: The cleverref package has a \crefrange and accompanying \crefrangeformat to handle this.

**Comment by tgkolda** [comment]
Fixed; waiting for SIAM approval to close.

**Comment by JHainesSIAM** [comment]
Fix verified!
