### ISSUE TITLE
No italics on numbers in cref.

### ISSUE THREAD

**Issue by tgkolda** [tgkolda/siam-latex#29]
From James Haines email on 7/17/15, issue 12a.

If you have something like

\documentclass[final,leqno]{siamart}
\newsiamremark{hypothesis}{Hypothesis}
\crefname{hypothesis}{Hypothesis}{Hypotheses}
\begin{document}
\begin{hypothesis}\label{hyp1}
A short hypothesis.
\end{hypothesis}
\begin{hypothesis}\label{hyp2}
A short hypothesis.
\end{hypothesis}
Now let's refer to \cref{hyp1,hyp2}. \Cref{hyp1,hyp2} are useful.
Now let's refer to \cref{hyp1}. \Cref{hyp1} is useful.
\end{document}

The hypothesis headings come out “Hypothesis 1.” with the number in italic rather than upright as it should be. 

Also, it seems that if there’s a \cref command inside an italic environment, like this:

\documentclass[final,leqno]{siamart}
\begin{document}
\begin{theorem}\label{thm1}
A short theorem.
\end{theorem}
\begin{theorem}\label{thm2}
A short theorem that refers to \cref{thm1}.
\end{theorem}
\end{document}

There’s doesn’t appear to be an easy way to romanize just the number, in this instance the “1” in "Theorem 1." If we do the obvious “A short theorem that refers to \textup{\cref{thm1}}.”, it prints as

A short theorem that refers to Theorem 1.

**Comment by tgkolda** [comment]
John from Techsetters recommends: cleverref has some facilities for formatting the way cross-references are formatting. Try this:

```
  \crefdefaultlabelformat{\upshape#2#1#3}
```

**Comment by tgkolda** [comment]
Can be closed pending SIAM approval.

**Comment by JHainesSIAM** [comment]
Steve reports that the \cref commands are coming out with upright numbers in italic environments. Also, numbers in italic things like “Remark 1.” were coming out upright.
However, he says we don’t get proper italic corrections unless we use \textup to do it. I am sending an email with his test files and altered cls file.

**Comment by tgkolda** [comment]
Should be fixed now, pending approval by James.

**Comment by tgkolda** [comment]
Fixed now.
