### ISSUE TITLE
Software citation

### ISSUE THREAD

**Issue by rjleveque** [tgkolda/siam-latex#3]
Regarding the last issue mentioned in https://github.com/tgkolda/siam-latex/blob/master/requirements.md

```
@misc{clawpack,
  title={Clawpack software},
  author={{Clawpack Development Team}},
  url={http://www.clawpack.org},
  note={Version x.y},
  year={2013}}
```

with two sets of braces around the "author" results in "Clawpack Development Team" in the bibliography (alphabetized at C) rather than "C. D. Team".

More generally -- how much guidance do we want to give on how to cite software?  Some packages explain how to cite in their documentation, many don't.

**Comment by tgkolda** [comment]
It would be nice to have an example of citing software, just to show some best practices. For instance, you probably want the version to be in the title and not as a note, because otherwise the version is at the very end of the citation, after the year.

**Comment by tgkolda** [comment]
This has been added in the last commit, though I forgot to explicitly cite this issue.
