### ISSUE TITLE
Linking problems with cref.

### ISSUE THREAD

**Issue by tgkolda** [tgkolda/siam-latex#30]
From James Haines email on 7/17/15, issue 12b.

Another concern discovered with testing \cref is that, rather than just the number being clickable in a link (i.e., “Table~\ref{xxx}”), if you type “\cref{xxx}” the whole phrase “Table 1” (or whatever) will be a clickable link. However, we are finding that either the phrase “Table 1” won’t be hyphenated/justified (if “breaklinks” is turned off) or it won’t link to anything if it breaks across two lines (if “breaklinks” is turned on).

**Comment by tgkolda** [comment]
Is this true in PDF or just DVI/PS? Can you provide a small example? Thanks!

**Comment by JHainesSIAM** [comment]
Examples sent via email.

**Comment by JHainesSIAM** [comment]
The split links work in the tex>dvi>ps>pdf cycle with:

   \usepackage{hypdvips}

This should **_not**_ be part of the class, since non-dvips users (pdfLaTeX users, for sure) will get errors.

One could add a class option to use this, though.

**Comment by JHainesSIAM** [comment]
We also confirmed that the link-splitting capability is built in with pdfLaTeX so it was only in the tex>dvi>ps>pdf cycle that this was a problem.

**Comment by tgkolda** [comment]
I'm going to leave this to post-production.
