### ISSUE TITLE
SIAM style manual updated regarding font of algorithm title.

### ISSUE THREAD

**Issue by tgkolda** [tgkolda/siam-latex#35]

**Comment by tgkolda** [comment]
Can be any font, and the SIAM style manual will be updated. Do include instructions in the appendix about how to make the font be small caps.

**Comment by tgkolda** [comment]
Added appendix in the documentation to explain how to change the font to small caps.

**Comment by JHainesSIAM** [comment]
Kelly Thomas confirmed on 12/9/15 that this had been added to the SIAM style manual as discussed.
