### ISSUE TITLE
Add DOI instructions to SIAM Style Manual

### ISSUE THREAD

**Issue by tgkolda** [tgkolda/siam-latex#36]
Authors should be required to provide the DOIs. If they do not provide them, they will be requested during the copyediting phase. The SIAM style manual will be updated to reflect this.

**Comment by tgkolda** [comment]
Added note in the documentation for the SIAM latex class, but the SIAM style guide still needs to be updated.

**Comment by JHainesSIAM** [comment]
Kelly Thomas confirmed on 12/9/15 that this had been added to the SIAM style manual as discussed.
