### ISSUE TITLE
amsmath

### ISSUE THREAD

**Issue by rjleveque** [tgkolda/siam-latex#4]
At the beginning of Section 4, along with the reference `\cite{MiGo04}`, it might be useful to point readers to online info about `amsmath`? Such as
- ftp://ftp.ams.org/pub/tex/doc/amsmath/short-math-guide.pdf
- ftp://ftp.ams.org/pub/tex/doc/amsmath/amsldoc.pdf

which can be found from http://www.ams.org/publications/authors/tex/amslatex and are
useful for looking up how to do things, or finding symbols.

**Comment by tgkolda** [comment]
Definitely. Please make the change at your convenience.

**Comment by tgkolda** [comment]
Added,
