### ISSUE TITLE
Spacing after appendix section heading

### ISSUE THREAD

**Issue by JHainesSIAM** [tgkolda/siam-latex#41]
Steve noticed that we are best off starting an appendix section like this:

\section{An appendix}\label{appA}%
Here is the start of the appendix.

If you don’t have that % to “attach” the \label to the “Here”, you get too much space between “An appendix.” and “Here”.

**Comment by tgkolda** [comment]
Yes, there is a comment about this in the documentation. I don't know how to fix it. The same problem existed with the previous style file.
