### ISSUE TITLE
Cref - Inconsistent equation linking?

### ISSUE THREAD

**Issue by JHainesSIAM** [tgkolda/siam-latex#43]
Example doc:

\documentclass[final,leqno]{siamart}

\begin{document}

Some equations:
\begin{align}
a &= b+c, \label{eq1} \
d &= e+f, \label{eq2} 
\end{align}

\Cref{eq1,eq2}.

\begin{theorem}\label{thm1}
A theorem.
\end{theorem}

\begin{theorem}\label{thm2}
A theorem.
\end{theorem}

\Cref{thm1,thm2}.

\end{document}

The first “1” in the example is a link to equation (1), “(2)” (i.e., the number plus the parentheses) is a link to equation (2), “Theorems 1” is a link to Theorem 1, and that last “2” is a link to Theorem 2.

Cref doesn't appear to be totally consistent what text it turns into a link.  What behavior is intended?  We expected the links to turn out as they did for the Theorems, but were surprised by the equations being treated differently.

**Comment by rjleveque** [comment]
I had to change `\` to `\\` at the end of `eq1` to get this to run.

I guess you expect "Equations (1)" to be highlighted rather than just "(1)"?

This probably has to do with suppressing "Equation" except when it's at the start of a sentence whereas "Theorem" always appears.

**Comment by tgkolda** [comment]
It wasn't CREF but rather our redefinition of how to handle equations (so that the word equations doesn't appear except at the beginning of a sentence). It's now fixed.
