### ISSUE TITLE
Author first names are not abbreviated

### ISSUE THREAD

**Issue by tgkolda** [tgkolda/siam-latex#45]

**Comment by rjleveque** [comment]
Do you mean in the bibliography?  If so, this is something I've run in to with some coauthors `.bib` files including full names when I only want initials in the bibliography.

I think if line 171 is used in `siamplain.bst` it forces using abbreviations, if I remember right.

https://github.com/tgkolda/siam-latex/blob/master/siamlatex/siamplain.bst#L171

Can this be provided as an option somehow?

**Comment by tgkolda** [comment]
Changed siamplain.bst to fix this.
