### ISSUE TITLE
ifpdf use package epstopdf

### ISSUE THREAD

**Issue by JHainesSIAM** [tgkolda/siam-latex#46]
John from Techsetters recommends incorporating something along the lines of the following to enable EPS figures to run with the macros while using pdfLaTeX by converting EPS to PDF on-the-fly:

\RequirePackage{ifpdf}
\ifpdf
\RequirePackage{color}
\definecolor{header1}{cmyk}{0,0,0,1}
\definecolor{blue1}{cmyk}{0,0,0,1}
\definecolor{blue2}{cmyk}{0,0,0,1}
\definecolor{maroon}{cmyk}{0,0,0,1}
\definecolor{gold1}{cmyk}{0,0,0,1}
\definecolor{gray}{cmyk}{0,0,0,1}
\definecolor{green1}{cmyk}{0,0,0,1}
\definecolor{proofcolor}{cmyk}{0,0,0,1}
\definecolor{red1}{cmyk}{0,0,0,1}
\definecolor{orange1}{cmyk}{0,0,0,1}
\definecolor{strip}{cmyk}{0,0,0,1}
\RequirePackage{graphics,graphicx}
\usepackage{epstopdf}
\RequirePackage[colorlinks]{hyperref}
\hypersetup{colorlinks,naturalnames=false,hypertexnames=false,breaklinks}
\urlstyle{same}
\newcommand{\mref}[1]{\href{mailto:#1}{#1}}
\def\wwwbrowser{C:\string\Program\space
Files\string\Plus!\string\Microsoft\space
Internet\string\iexplore.exe}
\definecolor{extlink}{cmyk}{0,0,0,1}
\definecolor{intlink}{cmyk}{0,0,0,1}
\definecolor{softpage}{cmyk}{0,0,0,1}
\def\@linkcolor{intlink}
\def\@anchorcolor{black}
\def\@citecolor{intlink}
\def\@filecolor{cyan}
\def\@urlcolor{extlink}
\def\@menucolor{red}
\newcommand{\email}[1]{\protect\href{mailto:#1}{#1}}
\newcommand{\web}[1]{\href{#1}{#1}}
\else%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%not pdflatex
\RequirePackage[dvips]{color}
\definecolor{header1}{cmyk}{0,0,0,1}
\definecolor{blue1}{cmyk}{0,0,0,1}
\definecolor{blue2}{cmyk}{0,0,0,1}
\definecolor{maroon}{cmyk}{0,0,0,1}
\definecolor{gold1}{cmyk}{0,0,0,1}
\definecolor{gray}{cmyk}{0,0,0,1}
\definecolor{green1}{cmyk}{0,0,0,1}
\definecolor{proofcolor}{cmyk}{0,0,0,1}
\definecolor{red1}{cmyk}{0,0,0,1}
\definecolor{orange1}{cmyk}{0,0,0,1}
\definecolor{strip}{cmyk}{0,0,0,1}
\RequirePackage[dvips]{graphics,graphicx}
\RequirePackage[colorlinks,pdfmark,dvips]{hyperref}
\hypersetup{colorlinks,pdfmark,dvips,naturalnames=false,hypertexnames=false,breaklinks}
\urlstyle{same}
\usepackage{breakurl}
\usepackage{hypdvips}
\newcommand{\mref}[1]{\burlalt{mailto:#1}{#1}}
\def\wwwbrowser{C:\string\Program\space
Files\string\Plus!\string\Microsoft\space
Internet\string\iexplore.exe}
\definecolor{extlink}{cmyk}{0,0,0,1}
\definecolor{intlink}{cmyk}{0,0,0,1}
\definecolor{softpage}{cmyk}{0,0,0,1}
\def\@linkcolor{intlink}
\def\@anchorcolor{black}
\def\@citecolor{intlink}
\def\@filecolor{cyan}
\def\@urlcolor{extlink}
\def\@menucolor{red}
\newcommand{\email}[1]{\protect\href{mailto:#1}{#1}}
\newcommand{\web}[1]{\href{#1}{#1}}
\fi%%%%%%%%end of ifpdf

**Comment by tgkolda** [comment]
I don't understand this comment - what is this fixing?

**Comment by JHainesSIAM** [comment]
According to John, it will eliminate the need for SIAM and Techsetters to use dviwindo for handling papers with EPS images.  We will already be switching over to pdflatex for handling papers with png, jpg, and pdf images and are timing that to go along with the launch of the new macros.

**Comment by tgkolda** [comment]
This seems overly complicated for the style file itself. Much of this is colors and other issues that seemingly have nothing to do with EPS images. I would suggest that these changes just be made in production or we find a simpler version.

**Comment by JHainesSIAM** [comment]
Will be added by SIAM and Techsetters to their in-house version if felt appropriate and useful.
