### ISSUE TITLE
`\cref` macro doesn't produce "section"

### ISSUE THREAD

**Issue by mpf** [tgkolda/siam-latex#7]
The [SIAM Style Manual](https://www.siam.org/journals/pdf/stylemanual.pdf) (p31) requires references to section numbers to use the word "section", rather than the symbol "§", e.g., "see section 3.2", rather than "see §3.2". The class file, however, implements the former.

Truth is, I prefer the section symbol, and use it by default, only to find myself changing them all back to SIAM's preferred "section" on submission.

Do we need to adhere to SIAM's style, or does the revised style file imply our request for SIAM to modify the current requirements?

**Comment by tgkolda** [comment]
Ah-ha. I obviously did not read the style manual in detail. Thanks for catching this. We can certainly ask SIAM to reconsider. Meanwhile, I will fix this to adhere to the style manual.

**Comment by tgkolda** [comment]
Fixed, but not sure how to mark as such.
